<h1>All addresses</h1>
<?php if (isset($users)) : ?>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Filter by user</label>
        </div>
        <select class="custom-select" id="inputGroupSelect01">
            <option selected value="0">All</option>
            <?php foreach ($users as $user) : ?>
                <option value="<?= $user->id ?>"><?= $user->getFullName() ?></option>
            <?php endforeach; ?>
        </select>
    </div>
<?php endif; ?>
<div id="noResult">
    <p>There is no one address for this user.</p>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">City</th>
        <th scope="col">Postcode</th>
        <th scope="col">Region</th>
        <th scope="col">Street</th>
        <th scope="col">Owner</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>
